name: Main Deploy Workflow

on:
    workflow_dispatch:
        inputs:
            build-status:
                description: "Choose the build status for the demo"
                type: choice
                choices: 
                    - "success"
                    - "failure"
                default: "success"
                required: true

jobs:
  call-build:
    uses: ./.github/workflows/o-workflow.yml
    with:
      build-status: ${{ github.event.inputs.build-status }}

  deploy:
    runs-on: ubuntu-latest
    needs: call-build
    if: ${{ needs.build.outputs.build-status == 'success' }}
    steps:
      - name: Deploy
        run: echo "Deploy"